### ISSUE TITLE
Node.js port?

### ISSUE THREAD

**Issue by zeno** [WhichBrowser/Parser#14]
Hey Niels, your library looks pretty precious :-)

Have you ever had requests for porting it to Node.js? We might be interested in doing that... In the Node world there's [platform.js](https://github.com/bestiejs/platform.js) which is nice, but WhichBrowser seems even more powerful (despite the fact it lacks unit testing, whereas platform.js doesn't).

**Comment by timaschew** [comment]
why nodejs?

If I understand it right, you don't need any server to handle it.
You already provide a bower solution, right? And it works standalone (without any php)?
So then you can do everything in the client.

BTW: I would do a note at the beginning of the readme that you don't need php.
https://github.com/WhichBrowser/WhichBrowser#requirements this is not true since you can use bower Javascript / client only

**Comment by DoctorDimon** [comment]
+1 for a nodejs port

**Comment by NielsLeenheer** [comment]
@timaschew Actually, you do need PHP. The detection is server side, but the results can be used client side.

**Comment by naomik** [comment]
+1 for a JS port. I'm failing to see the reason a backend component is even required at all. Any reasoning?

**Comment by c1moore** [comment]
+1 for Nodejs port

**Comment by baptistebriel** [comment]
+1

**Comment by knutole** [comment]
:+1:

**Comment by NielsLeenheer** [comment]
I'm not sure I'll have time for a Node.js port at this time. But I'll leave this bug open as a reminder.

**Comment by NielsLeenheer** [comment]
I'n closing this bug now as I don't have time to do a Node.js port in the foreseeable future.

**Comment by mariotsi** [comment]
I made a Node.js version because I can't find any other library with this grade of detection rate. You can find it here https://www.npmjs.com/package/which-browser
