### ISSUE TITLE
Include Parser / Testrunner / Server / ...as a composer dependency here

### ISSUE THREAD

**Issue by ThaDafinser** [WhichBrowser/Parser#52]
Its seems that the splitted packages are currently just a copy out from this main repo.

Currently the Testrunner cannot be autoloaded and the filenames are still lowercase, which prevents from installing correctly. ( i had a PR, but then noticed it's corrected here partly already)
https://github.com/WhichBrowser/Testrunner

I think correct would be to develop the Testrunner at the Testrunner repo and include it here as composer dependency. Or another way would be a git submodule.

But having just a copy of the sources will always lead to differences.

What do you think?

**Comment by NielsLeenheer** [comment]
Yeah, I'm not too happy about his. 

Right now the individual Parser, Testrunner and Server repositories are there just to provide the composer packages. All the development is done here in the WhichBrowser repository where all the source code lives before it is split into the separate packages by a grunt build and release task.

That also means that things like the testrunner must work with composer and also standalone. 

I'd rather not develop Testrunner standalone, because that would mean any change to Parser would mean I need to change Testrunner and release a package before I can test that change. Git submodules may work, but that would still mean two separate methods for loading the classes.

Not sure how to do this.

**Comment by ThaDafinser** [comment]
> I'd rather not develop Testrunner standalone, because that would mean any change to Parser would mean I need to change Testrunner and release a package before I can test that change.

You dont need to release a package to test the changes. You can also load the dev branch with composer https://packagist.org/packages/whichbrowser/parser#dev-master

You just need to set the minimum stability flag correctly for that.
So this would be no problem.

It's just another dev workflow, but it should work smoothly when you are used to it.

**Comment by NielsLeenheer** [comment]
Wouldn't that stil mean two separate environments:
- One with testrunner as a composer dependency of the parser repository
- One with testrunner and parser both installed using composer

**Comment by NielsLeenheer** [comment]
I'm still trying to get my head around this.

Do you propose I have a dev-require for Testrunner in the Parser package?

Wouldn't that stil mean two separate environments:
- One with Testrunner as a composer dependency of the Parser repository
- One with Testrunner and Parser both installed using composer

And because Testrunner also has a requirement for Parser, wouldn't that also mean that Parser itself would also be installed in the vendor directory of the Parser repository? And how would the Testrunner then know must test with the version of the repository instead of the composer package.

**Comment by NielsLeenheer** [comment]
Or should I have a dev-require for the Parser package in the Testrunner?

But once again that would mean two separate environments:

- One with Testrunner and Parser both installed using composer
- One with Parser as a composer dependency of the Testrunner repository

**Comment by ThaDafinser** [comment]
I would suggest doing it this way.

When testrunner can only be run with `parser` together it's a bidirectional relation and i would merge those two repos too one - the `parser`

So you only have 2 packages:
- the metapackage with the server, where u include `whichbrowser/whichbrowser`
- and `whichbrowser/parser` where u can the parsing logic with tests

`whichbrowser/whichbrowser`
```
"require": {
  "whichbrowser/parser": "...",
}
```

To seperate `parser` and `tests` inside the package you just create two folders like here `src` and `tests` https://github.com/ThaDafinser/UserAgentParser

Autoloading can also be splitted between dev and production:
https://github.com/ThaDafinser/UserAgentParser/blob/master/composer.json#L44

**Comment by NielsLeenheer** [comment]
Right, incorporating the testrunner in the parser package will probably be the easiest. I'll try to look into it over the weekend.

**Comment by NielsLeenheer** [comment]
- WhichBrowser/WhichBrowser is effectively removed.
- WhichBrowser/Testrunner is merged into WhichBrowser/Parser.
- WhichBrowser/Parser is now used for ongoing development.
- WhichBrowser/Server is now used for ongoing development. 

To do:
- release updated packages
- abandon the whichbrowser/testrunner package

**Comment by ThaDafinser** [comment]
Sounds good :yum: 

Two repos for dev are a good choice

**Comment by NielsLeenheer** [comment]
Released updated packages:
- whichbrowser/parser
- whichbrowser/server

Deleted package:
- whichbrowser/testrunner

This should have no effect on UserAgentParser. But it does mean UserAgentParserComparison is currently broken because the `whichbrowser/testrunner` package is no longer available separately. It is now in the bin directory of the `whichbrowser/parser` package.

**Comment by ThaDafinser** [comment]
Cool thing. I will dig into it ASAP.

I changed `UserAgentParserComparison` completely local, so i can add UA strings always and then run some result comparison later (step by step).

It's currently running since 3 days on a free AWS tier...i hope it will be enough :+1: 

When the 1.000k agents are analyzed i will publish the results again.

**Comment by ThaDafinser** [comment]
BTW huge +1 for all the latest improvements here. Codebase is a lot clearer to read and understand now :smile:

**Comment by NielsLeenheer** [comment]
Thanks! It was long overdue.

I'm still running into an issue though. Because tests/src is in 'autoload-dev', runner.php will fail when installed as a package, because it can't find the underlying classes. I guess the only way to solve this is to make add tests/src to regular 'autoload'.
